
spring.datasource:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_movie?serverTimezone=UTC
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver

server.port: 8080

swagger.enabled: true
springfox.documentation.swagger.v2.path: /swagger/v2/api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_ENUMS: true

spring.mvc.view.prefix: /templates/
spring.mvc.view.suffix: .html

Dfile.encoding: UTF-8
Dsun.jnu.encoding: UTF-8