#mvn spring-boot:run -Dspring-boot.run.profiles=test

spring.datasource:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_movie?serverTimezone=UTC
  username: ruut
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver

server.port: 8080

springdoc:api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  jackson: # <-- Toto je naše nové nastavení
    mapper:
      accept-case-insensitive-enums: true

#spring.mvc.view.prefix: /templates/
#spring.mvc.view.suffix: .html

Dfile.encoding: UTF-8
Dsun.jnu.encoding: UTF-8

cz.dvorakv:
  genres[0]: sci-fi
  genres[1]: animated